---
kind: pipeline
name: compliance

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - pull_request

steps:
  - name: check
    pull: always
    image: golang:1.14
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - make build
      - make lint
      - make vet

---
kind: pipeline
name: build-master

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: build
    pull: always
    image: techknowlogick/xgo:latest
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - make build